name: Backend-CI

on:
  push:
  pull_request:

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: DFAU/toujou-ci/.github/workflows/backend-ci.yml@main
    # customize steps with e.g. with: run-functional-tests: false
    secrets: inherit
    with:
      run-functional-tests: false
      run-unit-tests: false
